/* automatically generated by Makefile. */
#define EB_VERSION_STRING "4.4.3-20120704"
#define EB_VERSION_MAJOR 4
#define EB_VERSION_MINOR 4

// BEGIN jichi 3/28/2013
//#define EB_ENABLE_EBNET 1
#ifdef _MSC_VER
# include <inttypes.h>
  typedef long ssize_t;
#endif // _MSC_VER
// END jichi 3/28/2013
