#ifndef QTEMBEDPLUGIN_H
#define QTEMBEDPLUGIN_H

// qtembedplugin.h
// 2/1/2013 jichi

#ifndef QTEMBEDPLUGIN_BEGIN_NAMESPACE
# define QTEMBEDPLUGIN_BEGIN_NAMESPACE namespace QtEmbedPlugin {
#endif
#ifndef QTEMBEDPLUGIN_END_NAMESPACE
# define QTEMBEDPLUGIN_END_NAMESPACE   } // namespace QtEmbedPlugin
#endif

QTEMBEDPLUGIN_BEGIN_NAMESPACE
QTEMBEDPLUGIN_END_NAMESPACE

#endif // QTEMBEDPLUGIN_H
