#!/bin/bash
# 9/28/2013 jichi
ME="$(basename "$0")"
cd "$(dirname "$0")"

cd ../../.. # Come back to VNR/Library

MACPORTS_HOME=/opt/local
DARWINE_HOME=/Applications/Wine.app/Contents/Resources
export PATH=$PATH:$MACPORTS_HOME/bin:$DARWINE_HOME/bin

die()
{
  >&2 echo "$@"
  exit 1
}

require()
{
  local i
  for i; do
    which "$i" >/dev/null 2>&1 || \
      die "$ME: cannot find '$i' in PATH, ABORT"
  done
}
require wine
WINE=wine

export LANG=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF-8

#cd ..
#exec wine "Visual Novel Reader" "$@"

PYTHON=Frameworks/Python/pythonw.exe
FLAGS=-B
APP=Frameworks/Sakura/py/apps/reader
#APP_OPT=--debug
#echo "$ME: $WINE $PYTHON $APP $@"
exec $WINE "$PYTHON" $FLAGS "$APP" "$@"

# EOF
