namespace AITalk
{
    using System;

    public enum AIAudioResultCode
    {
        AIAUDIOERR_ALREADY_OPENED = 11,
        AIAUDIOERR_DEVICE_INVALIDATED = -21,
        AIAUDIOERR_INTERNAL_ERROR = -1,
        AIAUDIOERR_INVALID_ARGUMENT = -3,
        AIAUDIOERR_INVALID_CALL = -101,
        AIAUDIOERR_INVALID_EVENT_ORDINAL = -102,
        AIAUDIOERR_NO_AUDIO_HARDWARE = -20,
        AIAUDIOERR_NO_NOTIFICATION_CALLBACK = 0x67,
        AIAUDIOERR_NO_PLAYING = 0x6f,
        AIAUDIOERR_NOT_INITIALIZED = -10,
        AIAUDIOERR_NOT_OPENED = -11,
        AIAUDIOERR_OUT_OF_MEMORY = -100,
        AIAUDIOERR_SUCCESS = 0,
        AIAUDIOERR_UNSUPPORTED = -2,
        AIAUDIOERR_WAIT_TIMEOUT = -4,
        AIAUDIOERR_WRITE_FAULT = -201
    }
}

