namespace AITalk
{
    using System;

    public enum AITalkResultCode
    {
        AITALKERR_ALREADY_INITIALIZED = 10,
        AITALKERR_ALREADY_LOADED = 11,
        AITALKERR_FILE_NOT_FOUND = -1001,
        AITALKERR_INSUFFICIENT = -20,
        AITALKERR_INTERNAL_ERROR = -1,
        AITALKERR_INVALID_ARGUMENT = -3,
        AITALKERR_INVALID_JOBID = -202,
        AITALKERR_LICENSE_ABSENT = -100,
        AITALKERR_LICENSE_EXPIRED = -101,
        AITALKERR_LICENSE_REJECTED = -102,
        AITALKERR_NOMORE_DATA = 0xcc,
        AITALKERR_NOT_INITIALIZED = -10,
        AITALKERR_NOT_LOADED = -11,
        AITALKERR_PARTIALLY_REGISTERED = 0x15,
        AITALKERR_PATH_NOT_FOUND = -1002,
        AITALKERR_READ_FAULT = -1003,
        AITALKERR_SUCCESS = 0,
        AITALKERR_TOO_MANY_JOBS = -201,
        AITALKERR_UNSUPPORTED = -2,
        AITALKERR_USERDIC_LOCKED = -1011,
        AITALKERR_USERDIC_NOENTRY = -1012,
        AITALKERR_WAIT_TIMEOUT = -4
    }
}

